cat <<'EOF' |

kind: ConfigMap
metadata:
  name: grafana-agent
apiVersion: v1
data:
  agent.yaml: |    
    server:
      http_listen_port: 12345
    prometheus:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        external_labels:
          cluster: cloud
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 155529
            password: eyJrIjoiMjFhMTk4M2ZkOThmMDQ0YTU3OGM4YTM0MzEzYmY2OTJkMjUzNjViYyIsIm4iOiJtdWhhbW1hZGlyc2FseXVudXMtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjUxODY4Nn0=
        scrape_configs:
        - job_name: integrations/docker
          static_configs:
            - targets: ['localhost:8080']
        - job_name: integrations/kubernetes/cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          metric_relabel_configs:
            - action: drop
              regex: container_([a-z_]+);
              source_labels:
                - __name__
                - image
            - action: drop
              regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
              source_labels:
                - __name__
          relabel_configs:
            - replacement: kubernetes.default.svc.cluster.local:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        - job_name: integrations/kubernetes/kubelet
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - replacement: kubernetes.default.svc.cluster.local:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/${1}/proxy/metrics
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        
    integrations:
      prometheus_remote_write:
      - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: 155529
          password: eyJrIjoiMjFhMTk4M2ZkOThmMDQ0YTU3OGM4YTM0MzEzYmY2OTJkMjUzNjViYyIsIm4iOiJtdWhhbW1hZGlyc2FseXVudXMtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjUxODY4Nn0=
      elasticsearch_exporter:
        enabled: true
        address: http://localhost:9200
      
    loki:
      configs:
      - name: integrations
        clients:
        - url: https://logs-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 76735
            password: eyJrIjoiMjFhMTk4M2ZkOThmMDQ0YTU3OGM4YTM0MzEzYmY2OTJkMjUzNjViYyIsIm4iOiJtdWhhbW1hZGlyc2FseXVudXMtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjUxODY4Nn0=
          external_labels:
            cluster: cloud
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
    
EOF
(export NAMESPACE=monitoring && kubectl apply -n $NAMESPACE -f -)