# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    meta.helm.sh/release-name: brimoid-fe
    meta.helm.sh/release-namespace: brimoid
  creationTimestamp: "2021-08-18T03:55:53Z"
  generation: 13
  labels:
    app.kubernetes.io/instance: brimoid-fe
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: brimoid
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: brimoid-0.1.0
  name: brimoid-fe
  namespace: brimoid
  resourceVersion: "45909620"
  selfLink: /apis/apps/v1/namespaces/brimoid/deployments/brimoid-fe
  uid: a264babc-95e1-4f30-af1a-2b97e312d5a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: brimoid-fe
      app.kubernetes.io/name: brimoid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: brimoid-fe
        app.kubernetes.io/name: brimoid
    spec:
      containers:
      - image: gcr.io/bri-embrio-dev/brimoid-fe:2d00550
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: brimoid
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: brimoid-fe
      serviceAccountName: brimoid-fe
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-11T07:26:41Z"
    lastUpdateTime: "2021-09-11T07:26:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-18T13:43:23Z"
    lastUpdateTime: "2021-09-13T08:46:13Z"
    message: ReplicaSet "brimoid-fe-b4557cfc8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
